name: medallion
profile: medallion
version: 1.0
config-version: 2

models:
  medallion:
    bronze:
      +materialized: view   # ignored, since sources only
    silver:
      +schema: silver
      +catalog: demo
      +file_format: iceberg
    gold:
      +schema: gold
      +catalog: demo
      +file_format: iceberg
