version: 2

models:
  - name: person
    columns:
      - name: person_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: birth_year
      - name: death_year
  - name: role
    columns:
      - name: role_id
        tests:
          - not_null
          - unique
      - name: role_name
        tests:
          - not_null
          - unique
  - name: role_person
    columns:
      - name: role_id
        tests:
          - not_null
          - relationships:
              to: ref('role')
              field: role_id
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('person')
              field: person_id
      - name: job
# Add unique the composite role_id, person_id with dbt-utils
  - name: title_type
    columns:
      - name: title_type_id
        tests:
          - not_null
          - unique
      - name: title_type_name
        tests:
          - not_null
          - unique
  - name: genre
    columns:
      - name: genre_id
        tests:
          - not_null
          - unique
      - name: genre_name
        tests:
          - not_null
          - unique
  - name: title
    columns:
      - name: title_id
        tests:
          - not_null
          - unique
      - name: title_type_id
        tests:
          - not_null
          - relationships:
              to: ref('title_type')
              field: title_type_id
      - name: primary_title
        tests:
          - not_null
      - name: original_title
        tests:
          - not_null
      - name: is_adult
        tests:
          - not_null
      - name: release_year
      - name: duration_minutes
      - name: average_rating
        tests:
          - not_null
      - name: number_of_votes
        tests:
          - not_null
  - name: genre_title
    columns:
      - name: genre_id
        tests:
          - not_null
          - relationships:
              to: ref('genre')
              field: genre_id
      - name: title_id
        tests:
          - not_null
          - relationships:
              to: ref('title')
              field: title_id
  - name: title_person
    columns:
      - name: title_id
        tests:
          - not_null
          - relationships:
              to: ref('title')
              field: title_id
      - name: person_id
        tests:
          - not_null
          - relationships:
              to: ref('person')
              field: person_id
      - name: role_id
        tests:
          - not_null
          - relationships:
              to: ref('role')
              field: role_id
      - name: job
      - name: number_of_roles
        tests:
          - not_null
      - name: characters
        tests:
          - not_null
  - name: region
    columns:
      - name: region_id
        tests:
          - not_null
          - unique
      - name: region_name
        tests:
          - not_null
          - unique
  - name: language
    columns:
      - name: language_id
        tests:
          - not_null
          - unique
      - name: language_name
        tests:
          - not_null
          - unique
  - name: attribute
    columns:
      - name: attribute_id
        tests:
          - not_null
          - unique
      - name: attribute_name
        tests:
          - not_null
          - unique
  - name: title_localized
    columns:
      - name: title_id
        tests:
          - not_null
          - relationships:
              to: ref('title')
              field: title_id
      - name: title
        tests:
          - not_null
      - name: ordering
        tests:
          - not_null
      - name: region_id
        tests:
          - not_null
          - relationships:
              to: ref('region')
              field: region_id
      - name: language_id
        tests:
          - not_null
          - relationships:
              to: ref('language')
              field: language_id
      - name: attribute_id
        tests:
          - not_null
          - relationships:
              to: ref('attribute')
              field: attribute_id
      - name: is_original_title
        tests:
          - not_null
  - name: title_episode
    columns:
      - name: title_id
        tests:
          - not_null
          - relationships:
              to: ref('title')
              field: title_id
      - name: parent_title_id
        tests:
          - not_null
          - relationships:
              to: ref('title')
              field: title_id
      - name: season_number
      - name: episode_number