version: 2

models:
  - name: person
    columns:
      - name: person_id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
      - name: birth_year
      - name: death_year
  - name: role
    columns:
      - name: role_id
        tests:
          - not_null
          - unique
      - name: role_name
        tests:
          - not_null
          - unique
  - name: role_person
    columns:
      - name: role_id
        tests:
          - not_null
      - name: person_id
        tests:
          - not_null
# Add unique the composite role_id, person_id with dbt-utils
  - name: title_type
    columns:
      - name: title_type_id
        tests:
          - not_null
          - unique
      - name: title_type_name
        tests:
          - not_null
          - unique
  - name: genre
    columns:
      - name: genre_id
        tests:
          - not_null
          - unique
      - name: genre_name
        tests:
          - not_null
          - unique
  - name: title
    columns:
      - name: title_id
        tests:
          - not_null
          - unique
      - name: title_type_id
        tests:
          - not_null
      - name: primary_title
        tests:
          - not_null
      - name: original_title
        tests:
          - not_null
      - name: is_adult
        tests:
          - not_null
      - name: release_year
      - name: duration_minutes