silver:
  target: local
  outputs:
    local:
      type: spark
      method: thrift
      host: spark-thrift-server
      port: 10000
      user: dbt
      schema: silver
      connect_retries: 5
      connect_timeout: 60
      retry_all: true

