version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: name_basics
      - name: title_principals
      - name: title_basics
      - name: title_ratings
      - name: title_akas
      - name: title_episode
